application:
  datasource: # in addition to the standard spring.datasource properties
    cachePrepStmts: true
    prepStmtCacheSize: 250
    prepStmtCacheSqlLimit: 2048
    useServerPrepStmts: true

spring:
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  application:
    name: Sensors
  profiles:
    active: dev
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;INIT=runscript from 'classpath:resources/db.sql'
    username: sa
    password:
    #driver-class-name: org.h2.jdbcx.JdbcDataSource
    #initialize: true
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    show-sql: true
    format_sql: true
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: true
    hibernate:
      ddl-auto: create-drop

server:
  port: 8080
logging:
  level:
    web: debug
